
brain:

    supress_warnings: true

    allow_system_aiml: true
    allow_learn_aiml: true
    allow_learnf_aiml: true

    files:
        license_keys: $BOT_ROOT/config/license.keys
        aiml:
            files: $BOT_ROOT/aiml
            extension: .aiml
            directories: true
        sets:
            files: $BOT_ROOT/sets
            extension: .txt
            directories: false
        maps:
            files: $BOT_ROOT/maps
            extension: .txt
            directories: false
        denormal: $BOT_ROOT/config/denormal.txt
        normal: $BOT_ROOT/config/normal.txt
        gender: $BOT_ROOT/config/gender.txt
        person: $BOT_ROOT/config/person.txt
        person2: $BOT_ROOT/config/person2.txt
        predicates: $BOT_ROOT/config/predicates.txt
        pronouns: $BOT_ROOT/config/pronouns.txt
        properties: $BOT_ROOT/config/properties.txt
        triples: $BOT_ROOT/config/triples.txt
        preprocessors: $BOT_ROOT/config/preprocessors.conf
        postprocessors: $BOT_ROOT/config/postprocessors.conf

    services:
        REST:
            path: programy.utils.services.rest.GenericRESTService
        Pannous:
            path: programy.utils.services.pannous.PannousService
            login: test-user
        Pandora:
            path: programy.utils.services.pandora.PandoraService
            botid: f5d922d97e345aa1
        Wikipedia:
            path: programy.utils.services.wikipediaservice.WikipediaService

bot:
    prompt: ">>>"
    initial_question: Hi, how can I help you today?
    default_response: Sorry, I don't have an answer for that!
    exit_response: So long, and thanks for the fish!
    override_predicates: true

rest:
  host: 127.0.0.1
  port: 5000
  debug: false