
pannous:
  file: programy.utils.services.pannous
  class: PannousService

pandora:
  file: programy.utils.services.pandora
  class: PandoraService

wikipedia:
  file: programy.utils.services.wikipedia
  class: WikipediaService

generic:
  file: programy.utils.services.generic
  class: GenericRESTService
